/*
Client Portal Web API

Client Poral Web API

API version: 1.0.0
Contact: e@e.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

import (
	"encoding/json"
)

// checks if the EnableDisableDeviceRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &EnableDisableDeviceRequest{}

// EnableDisableDeviceRequest struct for EnableDisableDeviceRequest
type EnableDisableDeviceRequest struct {
	Devicename *string `json:"devicename,omitempty"`
	DeviceId   *string `json:"deviceId,omitempty"`
	UiName     *string `json:"uiName,omitempty"`
	Enabled    *bool   `json:"enabled,omitempty"`
}

// NewEnableDisableDeviceRequest instantiates a new EnableDisableDeviceRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewEnableDisableDeviceRequest() *EnableDisableDeviceRequest {
	this := EnableDisableDeviceRequest{}
	return &this
}

// NewEnableDisableDeviceRequestWithDefaults instantiates a new EnableDisableDeviceRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewEnableDisableDeviceRequestWithDefaults() *EnableDisableDeviceRequest {
	this := EnableDisableDeviceRequest{}
	return &this
}

// GetDevicename returns the Devicename field value if set, zero value otherwise.
func (o *EnableDisableDeviceRequest) GetDevicename() string {
	if o == nil || IsNil(o.Devicename) {
		var ret string
		return ret
	}
	return *o.Devicename
}

// GetDevicenameOk returns a tuple with the Devicename field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EnableDisableDeviceRequest) GetDevicenameOk() (*string, bool) {
	if o == nil || IsNil(o.Devicename) {
		return nil, false
	}
	return o.Devicename, true
}

// HasDevicename returns a boolean if a field has been set.
func (o *EnableDisableDeviceRequest) HasDevicename() bool {
	if o != nil && !IsNil(o.Devicename) {
		return true
	}

	return false
}

// SetDevicename gets a reference to the given string and assigns it to the Devicename field.
func (o *EnableDisableDeviceRequest) SetDevicename(v string) {
	o.Devicename = &v
}

// GetDeviceId returns the DeviceId field value if set, zero value otherwise.
func (o *EnableDisableDeviceRequest) GetDeviceId() string {
	if o == nil || IsNil(o.DeviceId) {
		var ret string
		return ret
	}
	return *o.DeviceId
}

// GetDeviceIdOk returns a tuple with the DeviceId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EnableDisableDeviceRequest) GetDeviceIdOk() (*string, bool) {
	if o == nil || IsNil(o.DeviceId) {
		return nil, false
	}
	return o.DeviceId, true
}

// HasDeviceId returns a boolean if a field has been set.
func (o *EnableDisableDeviceRequest) HasDeviceId() bool {
	if o != nil && !IsNil(o.DeviceId) {
		return true
	}

	return false
}

// SetDeviceId gets a reference to the given string and assigns it to the DeviceId field.
func (o *EnableDisableDeviceRequest) SetDeviceId(v string) {
	o.DeviceId = &v
}

// GetUiName returns the UiName field value if set, zero value otherwise.
func (o *EnableDisableDeviceRequest) GetUiName() string {
	if o == nil || IsNil(o.UiName) {
		var ret string
		return ret
	}
	return *o.UiName
}

// GetUiNameOk returns a tuple with the UiName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EnableDisableDeviceRequest) GetUiNameOk() (*string, bool) {
	if o == nil || IsNil(o.UiName) {
		return nil, false
	}
	return o.UiName, true
}

// HasUiName returns a boolean if a field has been set.
func (o *EnableDisableDeviceRequest) HasUiName() bool {
	if o != nil && !IsNil(o.UiName) {
		return true
	}

	return false
}

// SetUiName gets a reference to the given string and assigns it to the UiName field.
func (o *EnableDisableDeviceRequest) SetUiName(v string) {
	o.UiName = &v
}

// GetEnabled returns the Enabled field value if set, zero value otherwise.
func (o *EnableDisableDeviceRequest) GetEnabled() bool {
	if o == nil || IsNil(o.Enabled) {
		var ret bool
		return ret
	}
	return *o.Enabled
}

// GetEnabledOk returns a tuple with the Enabled field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EnableDisableDeviceRequest) GetEnabledOk() (*bool, bool) {
	if o == nil || IsNil(o.Enabled) {
		return nil, false
	}
	return o.Enabled, true
}

// HasEnabled returns a boolean if a field has been set.
func (o *EnableDisableDeviceRequest) HasEnabled() bool {
	if o != nil && !IsNil(o.Enabled) {
		return true
	}

	return false
}

// SetEnabled gets a reference to the given bool and assigns it to the Enabled field.
func (o *EnableDisableDeviceRequest) SetEnabled(v bool) {
	o.Enabled = &v
}

func (o EnableDisableDeviceRequest) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o EnableDisableDeviceRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Devicename) {
		toSerialize["devicename"] = o.Devicename
	}
	if !IsNil(o.DeviceId) {
		toSerialize["deviceId"] = o.DeviceId
	}
	if !IsNil(o.UiName) {
		toSerialize["uiName"] = o.UiName
	}
	if !IsNil(o.Enabled) {
		toSerialize["enabled"] = o.Enabled
	}
	return toSerialize, nil
}

type NullableEnableDisableDeviceRequest struct {
	value *EnableDisableDeviceRequest
	isSet bool
}

func (v NullableEnableDisableDeviceRequest) Get() *EnableDisableDeviceRequest {
	return v.value
}

func (v *NullableEnableDisableDeviceRequest) Set(val *EnableDisableDeviceRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableEnableDisableDeviceRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableEnableDisableDeviceRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableEnableDisableDeviceRequest(val *EnableDisableDeviceRequest) *NullableEnableDisableDeviceRequest {
	return &NullableEnableDisableDeviceRequest{value: val, isSet: true}
}

func (v NullableEnableDisableDeviceRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableEnableDisableDeviceRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
