/*
Client Portal Web API

Client Poral Web API

API version: 1.0.0
Contact: e@e.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

import (
	"encoding/json"
)

// checks if the GetSecdefSchedule200ResponseSchedulesInner type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetSecdefSchedule200ResponseSchedulesInner{}

// GetSecdefSchedule200ResponseSchedulesInner struct for GetSecdefSchedule200ResponseSchedulesInner
type GetSecdefSchedule200ResponseSchedulesInner struct {
	ClearingCycleEndTime *int32 `json:"clearingCycleEndTime,omitempty"`
	// 20000101 stands for any Sat, 20000102 stands for any Sun, ... 20000107 stands for any Fri. Any other date stands for itself.
	TradingScheduleDate *int32                                                  `json:"tradingScheduleDate,omitempty"`
	Sessions            *GetSecdefSchedule200ResponseSchedulesInnerSessions     `json:"sessions,omitempty"`
	TradingTimes        *GetSecdefSchedule200ResponseSchedulesInnerTradingTimes `json:"tradingTimes,omitempty"`
}

// NewGetSecdefSchedule200ResponseSchedulesInner instantiates a new GetSecdefSchedule200ResponseSchedulesInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetSecdefSchedule200ResponseSchedulesInner() *GetSecdefSchedule200ResponseSchedulesInner {
	this := GetSecdefSchedule200ResponseSchedulesInner{}
	return &this
}

// NewGetSecdefSchedule200ResponseSchedulesInnerWithDefaults instantiates a new GetSecdefSchedule200ResponseSchedulesInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetSecdefSchedule200ResponseSchedulesInnerWithDefaults() *GetSecdefSchedule200ResponseSchedulesInner {
	this := GetSecdefSchedule200ResponseSchedulesInner{}
	return &this
}

// GetClearingCycleEndTime returns the ClearingCycleEndTime field value if set, zero value otherwise.
func (o *GetSecdefSchedule200ResponseSchedulesInner) GetClearingCycleEndTime() int32 {
	if o == nil || IsNil(o.ClearingCycleEndTime) {
		var ret int32
		return ret
	}
	return *o.ClearingCycleEndTime
}

// GetClearingCycleEndTimeOk returns a tuple with the ClearingCycleEndTime field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetSecdefSchedule200ResponseSchedulesInner) GetClearingCycleEndTimeOk() (*int32, bool) {
	if o == nil || IsNil(o.ClearingCycleEndTime) {
		return nil, false
	}
	return o.ClearingCycleEndTime, true
}

// HasClearingCycleEndTime returns a boolean if a field has been set.
func (o *GetSecdefSchedule200ResponseSchedulesInner) HasClearingCycleEndTime() bool {
	if o != nil && !IsNil(o.ClearingCycleEndTime) {
		return true
	}

	return false
}

// SetClearingCycleEndTime gets a reference to the given int32 and assigns it to the ClearingCycleEndTime field.
func (o *GetSecdefSchedule200ResponseSchedulesInner) SetClearingCycleEndTime(v int32) {
	o.ClearingCycleEndTime = &v
}

// GetTradingScheduleDate returns the TradingScheduleDate field value if set, zero value otherwise.
func (o *GetSecdefSchedule200ResponseSchedulesInner) GetTradingScheduleDate() int32 {
	if o == nil || IsNil(o.TradingScheduleDate) {
		var ret int32
		return ret
	}
	return *o.TradingScheduleDate
}

// GetTradingScheduleDateOk returns a tuple with the TradingScheduleDate field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetSecdefSchedule200ResponseSchedulesInner) GetTradingScheduleDateOk() (*int32, bool) {
	if o == nil || IsNil(o.TradingScheduleDate) {
		return nil, false
	}
	return o.TradingScheduleDate, true
}

// HasTradingScheduleDate returns a boolean if a field has been set.
func (o *GetSecdefSchedule200ResponseSchedulesInner) HasTradingScheduleDate() bool {
	if o != nil && !IsNil(o.TradingScheduleDate) {
		return true
	}

	return false
}

// SetTradingScheduleDate gets a reference to the given int32 and assigns it to the TradingScheduleDate field.
func (o *GetSecdefSchedule200ResponseSchedulesInner) SetTradingScheduleDate(v int32) {
	o.TradingScheduleDate = &v
}

// GetSessions returns the Sessions field value if set, zero value otherwise.
func (o *GetSecdefSchedule200ResponseSchedulesInner) GetSessions() GetSecdefSchedule200ResponseSchedulesInnerSessions {
	if o == nil || IsNil(o.Sessions) {
		var ret GetSecdefSchedule200ResponseSchedulesInnerSessions
		return ret
	}
	return *o.Sessions
}

// GetSessionsOk returns a tuple with the Sessions field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetSecdefSchedule200ResponseSchedulesInner) GetSessionsOk() (*GetSecdefSchedule200ResponseSchedulesInnerSessions, bool) {
	if o == nil || IsNil(o.Sessions) {
		return nil, false
	}
	return o.Sessions, true
}

// HasSessions returns a boolean if a field has been set.
func (o *GetSecdefSchedule200ResponseSchedulesInner) HasSessions() bool {
	if o != nil && !IsNil(o.Sessions) {
		return true
	}

	return false
}

// SetSessions gets a reference to the given GetSecdefSchedule200ResponseSchedulesInnerSessions and assigns it to the Sessions field.
func (o *GetSecdefSchedule200ResponseSchedulesInner) SetSessions(v GetSecdefSchedule200ResponseSchedulesInnerSessions) {
	o.Sessions = &v
}

// GetTradingTimes returns the TradingTimes field value if set, zero value otherwise.
func (o *GetSecdefSchedule200ResponseSchedulesInner) GetTradingTimes() GetSecdefSchedule200ResponseSchedulesInnerTradingTimes {
	if o == nil || IsNil(o.TradingTimes) {
		var ret GetSecdefSchedule200ResponseSchedulesInnerTradingTimes
		return ret
	}
	return *o.TradingTimes
}

// GetTradingTimesOk returns a tuple with the TradingTimes field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetSecdefSchedule200ResponseSchedulesInner) GetTradingTimesOk() (*GetSecdefSchedule200ResponseSchedulesInnerTradingTimes, bool) {
	if o == nil || IsNil(o.TradingTimes) {
		return nil, false
	}
	return o.TradingTimes, true
}

// HasTradingTimes returns a boolean if a field has been set.
func (o *GetSecdefSchedule200ResponseSchedulesInner) HasTradingTimes() bool {
	if o != nil && !IsNil(o.TradingTimes) {
		return true
	}

	return false
}

// SetTradingTimes gets a reference to the given GetSecdefSchedule200ResponseSchedulesInnerTradingTimes and assigns it to the TradingTimes field.
func (o *GetSecdefSchedule200ResponseSchedulesInner) SetTradingTimes(v GetSecdefSchedule200ResponseSchedulesInnerTradingTimes) {
	o.TradingTimes = &v
}

func (o GetSecdefSchedule200ResponseSchedulesInner) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetSecdefSchedule200ResponseSchedulesInner) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.ClearingCycleEndTime) {
		toSerialize["clearingCycleEndTime"] = o.ClearingCycleEndTime
	}
	if !IsNil(o.TradingScheduleDate) {
		toSerialize["tradingScheduleDate"] = o.TradingScheduleDate
	}
	if !IsNil(o.Sessions) {
		toSerialize["sessions"] = o.Sessions
	}
	if !IsNil(o.TradingTimes) {
		toSerialize["tradingTimes"] = o.TradingTimes
	}
	return toSerialize, nil
}

type NullableGetSecdefSchedule200ResponseSchedulesInner struct {
	value *GetSecdefSchedule200ResponseSchedulesInner
	isSet bool
}

func (v NullableGetSecdefSchedule200ResponseSchedulesInner) Get() *GetSecdefSchedule200ResponseSchedulesInner {
	return v.value
}

func (v *NullableGetSecdefSchedule200ResponseSchedulesInner) Set(val *GetSecdefSchedule200ResponseSchedulesInner) {
	v.value = val
	v.isSet = true
}

func (v NullableGetSecdefSchedule200ResponseSchedulesInner) IsSet() bool {
	return v.isSet
}

func (v *NullableGetSecdefSchedule200ResponseSchedulesInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetSecdefSchedule200ResponseSchedulesInner(val *GetSecdefSchedule200ResponseSchedulesInner) *NullableGetSecdefSchedule200ResponseSchedulesInner {
	return &NullableGetSecdefSchedule200ResponseSchedulesInner{value: val, isSet: true}
}

func (v NullableGetSecdefSchedule200ResponseSchedulesInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetSecdefSchedule200ResponseSchedulesInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
