/*
Client Portal Web API

Client Poral Web API

API version: 1.0.0
Contact: e@e.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

import (
	"encoding/json"
)

// checks if the GetDeliveryOptions200ResponseEInner type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetDeliveryOptions200ResponseEInner{}

// GetDeliveryOptions200ResponseEInner device
type GetDeliveryOptions200ResponseEInner struct {
	// device name
	NM *string `json:"NM,omitempty"`
	// device id
	I *string `json:"I,omitempty"`
	// unique device id
	UI *string `json:"UI,omitempty"`
	// device is enabled or not 0-true, 1-false.
	A *string `json:"A,omitempty"`
}

// NewGetDeliveryOptions200ResponseEInner instantiates a new GetDeliveryOptions200ResponseEInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetDeliveryOptions200ResponseEInner() *GetDeliveryOptions200ResponseEInner {
	this := GetDeliveryOptions200ResponseEInner{}
	return &this
}

// NewGetDeliveryOptions200ResponseEInnerWithDefaults instantiates a new GetDeliveryOptions200ResponseEInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetDeliveryOptions200ResponseEInnerWithDefaults() *GetDeliveryOptions200ResponseEInner {
	this := GetDeliveryOptions200ResponseEInner{}
	return &this
}

// GetNM returns the NM field value if set, zero value otherwise.
func (o *GetDeliveryOptions200ResponseEInner) GetNM() string {
	if o == nil || IsNil(o.NM) {
		var ret string
		return ret
	}
	return *o.NM
}

// GetNMOk returns a tuple with the NM field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetDeliveryOptions200ResponseEInner) GetNMOk() (*string, bool) {
	if o == nil || IsNil(o.NM) {
		return nil, false
	}
	return o.NM, true
}

// HasNM returns a boolean if a field has been set.
func (o *GetDeliveryOptions200ResponseEInner) HasNM() bool {
	if o != nil && !IsNil(o.NM) {
		return true
	}

	return false
}

// SetNM gets a reference to the given string and assigns it to the NM field.
func (o *GetDeliveryOptions200ResponseEInner) SetNM(v string) {
	o.NM = &v
}

// GetI returns the I field value if set, zero value otherwise.
func (o *GetDeliveryOptions200ResponseEInner) GetI() string {
	if o == nil || IsNil(o.I) {
		var ret string
		return ret
	}
	return *o.I
}

// GetIOk returns a tuple with the I field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetDeliveryOptions200ResponseEInner) GetIOk() (*string, bool) {
	if o == nil || IsNil(o.I) {
		return nil, false
	}
	return o.I, true
}

// HasI returns a boolean if a field has been set.
func (o *GetDeliveryOptions200ResponseEInner) HasI() bool {
	if o != nil && !IsNil(o.I) {
		return true
	}

	return false
}

// SetI gets a reference to the given string and assigns it to the I field.
func (o *GetDeliveryOptions200ResponseEInner) SetI(v string) {
	o.I = &v
}

// GetUI returns the UI field value if set, zero value otherwise.
func (o *GetDeliveryOptions200ResponseEInner) GetUI() string {
	if o == nil || IsNil(o.UI) {
		var ret string
		return ret
	}
	return *o.UI
}

// GetUIOk returns a tuple with the UI field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetDeliveryOptions200ResponseEInner) GetUIOk() (*string, bool) {
	if o == nil || IsNil(o.UI) {
		return nil, false
	}
	return o.UI, true
}

// HasUI returns a boolean if a field has been set.
func (o *GetDeliveryOptions200ResponseEInner) HasUI() bool {
	if o != nil && !IsNil(o.UI) {
		return true
	}

	return false
}

// SetUI gets a reference to the given string and assigns it to the UI field.
func (o *GetDeliveryOptions200ResponseEInner) SetUI(v string) {
	o.UI = &v
}

// GetA returns the A field value if set, zero value otherwise.
func (o *GetDeliveryOptions200ResponseEInner) GetA() string {
	if o == nil || IsNil(o.A) {
		var ret string
		return ret
	}
	return *o.A
}

// GetAOk returns a tuple with the A field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetDeliveryOptions200ResponseEInner) GetAOk() (*string, bool) {
	if o == nil || IsNil(o.A) {
		return nil, false
	}
	return o.A, true
}

// HasA returns a boolean if a field has been set.
func (o *GetDeliveryOptions200ResponseEInner) HasA() bool {
	if o != nil && !IsNil(o.A) {
		return true
	}

	return false
}

// SetA gets a reference to the given string and assigns it to the A field.
func (o *GetDeliveryOptions200ResponseEInner) SetA(v string) {
	o.A = &v
}

func (o GetDeliveryOptions200ResponseEInner) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetDeliveryOptions200ResponseEInner) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.NM) {
		toSerialize["NM"] = o.NM
	}
	if !IsNil(o.I) {
		toSerialize["I"] = o.I
	}
	if !IsNil(o.UI) {
		toSerialize["UI"] = o.UI
	}
	if !IsNil(o.A) {
		toSerialize["A"] = o.A
	}
	return toSerialize, nil
}

type NullableGetDeliveryOptions200ResponseEInner struct {
	value *GetDeliveryOptions200ResponseEInner
	isSet bool
}

func (v NullableGetDeliveryOptions200ResponseEInner) Get() *GetDeliveryOptions200ResponseEInner {
	return v.value
}

func (v *NullableGetDeliveryOptions200ResponseEInner) Set(val *GetDeliveryOptions200ResponseEInner) {
	v.value = val
	v.isSet = true
}

func (v NullableGetDeliveryOptions200ResponseEInner) IsSet() bool {
	return v.isSet
}

func (v *NullableGetDeliveryOptions200ResponseEInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetDeliveryOptions200ResponseEInner(val *GetDeliveryOptions200ResponseEInner) *NullableGetDeliveryOptions200ResponseEInner {
	return &NullableGetDeliveryOptions200ResponseEInner{value: val, isSet: true}
}

func (v NullableGetDeliveryOptions200ResponseEInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetDeliveryOptions200ResponseEInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
