/*
Client Portal Web API

Client Poral Web API

API version: 1.0.0
Contact: e@e.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

import (
	"encoding/json"
)

// checks if the GetUnreadNumber200Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetUnreadNumber200Response{}

// GetUnreadNumber200Response struct for GetUnreadNumber200Response
type GetUnreadNumber200Response struct {
	// unread number
	BN *int32 `json:"BN,omitempty"`
}

// NewGetUnreadNumber200Response instantiates a new GetUnreadNumber200Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetUnreadNumber200Response() *GetUnreadNumber200Response {
	this := GetUnreadNumber200Response{}
	return &this
}

// NewGetUnreadNumber200ResponseWithDefaults instantiates a new GetUnreadNumber200Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetUnreadNumber200ResponseWithDefaults() *GetUnreadNumber200Response {
	this := GetUnreadNumber200Response{}
	return &this
}

// GetBN returns the BN field value if set, zero value otherwise.
func (o *GetUnreadNumber200Response) GetBN() int32 {
	if o == nil || IsNil(o.BN) {
		var ret int32
		return ret
	}
	return *o.BN
}

// GetBNOk returns a tuple with the BN field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetUnreadNumber200Response) GetBNOk() (*int32, bool) {
	if o == nil || IsNil(o.BN) {
		return nil, false
	}
	return o.BN, true
}

// HasBN returns a boolean if a field has been set.
func (o *GetUnreadNumber200Response) HasBN() bool {
	if o != nil && !IsNil(o.BN) {
		return true
	}

	return false
}

// SetBN gets a reference to the given int32 and assigns it to the BN field.
func (o *GetUnreadNumber200Response) SetBN(v int32) {
	o.BN = &v
}

func (o GetUnreadNumber200Response) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetUnreadNumber200Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.BN) {
		toSerialize["BN"] = o.BN
	}
	return toSerialize, nil
}

type NullableGetUnreadNumber200Response struct {
	value *GetUnreadNumber200Response
	isSet bool
}

func (v NullableGetUnreadNumber200Response) Get() *GetUnreadNumber200Response {
	return v.value
}

func (v *NullableGetUnreadNumber200Response) Set(val *GetUnreadNumber200Response) {
	v.value = val
	v.isSet = true
}

func (v NullableGetUnreadNumber200Response) IsSet() bool {
	return v.isSet
}

func (v *NullableGetUnreadNumber200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetUnreadNumber200Response(val *GetUnreadNumber200Response) *NullableGetUnreadNumber200Response {
	return &NullableGetUnreadNumber200Response{value: val, isSet: true}
}

func (v NullableGetUnreadNumber200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetUnreadNumber200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
