/*
Client Portal Web API

Client Poral Web API

API version: 1.0.0
Contact: e@e.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the IserverContractConidAlgosGet200ResponseInnerParametersInner type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &IserverContractConidAlgosGet200ResponseInnerParametersInner{}

// IserverContractConidAlgosGet200ResponseInnerParametersInner struct for IserverContractConidAlgosGet200ResponseInnerParametersInner
type IserverContractConidAlgosGet200ResponseInnerParametersInner struct {
	// The algo parameter
	Id string `json:"id"`
	// If true a value must be entered.
	Required *bool `json:"required,omitempty"`
	// Descriptive name of the parameter.
	Name *string `json:"name,omitempty"`
	// Format of the parameter.
	ValueClassName string `json:"valueClassName"`
	// Smallest value, only applies to parameters with valueClassName=Double.
	MinValue *float32 `json:"minValue,omitempty"`
	// Largest value, only applies to parameters with valueClassName=Double.
	MaxValue *float32 `json:"maxValue,omitempty"`
	// User configured preset for this parameter.
	DefaultValue *bool `json:"defaultValue,omitempty"`
	// The list of choices
	LegalStrings *string `json:"legalStrings,omitempty"`
	// Detailed description of the parameter.
	Description *string `json:"description,omitempty"`
	// The order in UI, used when building dynamic UI so that more important parameters are presented first.
	GuiRank *float32 `json:"guiRank,omitempty"`
	// If true, must specify parameter using market rule format. Only applies to parameters with valueClassName=Double.
	PriceMarketRule *bool `json:"priceMarketRule,omitempty"`
	// The rules that UI should apply to algo parameters depending on chosen order type:  * MKT:speedUp:=:no - hide SpeedUp param when MKT is chosen for order type.  * LMT:strategyType:<>:empty - strategyType param cannot be empty when LMT is chosen for order type.  * MKT:strategyType:=:Marketable - set strategyType param to Marketable and disable (no other choice) when MKT is chosen for order type.
	EnabledConditions *string `json:"enabledConditions,omitempty"`
}

type _IserverContractConidAlgosGet200ResponseInnerParametersInner IserverContractConidAlgosGet200ResponseInnerParametersInner

// NewIserverContractConidAlgosGet200ResponseInnerParametersInner instantiates a new IserverContractConidAlgosGet200ResponseInnerParametersInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewIserverContractConidAlgosGet200ResponseInnerParametersInner(id string, valueClassName string) *IserverContractConidAlgosGet200ResponseInnerParametersInner {
	this := IserverContractConidAlgosGet200ResponseInnerParametersInner{}
	this.Id = id
	this.ValueClassName = valueClassName
	return &this
}

// NewIserverContractConidAlgosGet200ResponseInnerParametersInnerWithDefaults instantiates a new IserverContractConidAlgosGet200ResponseInnerParametersInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewIserverContractConidAlgosGet200ResponseInnerParametersInnerWithDefaults() *IserverContractConidAlgosGet200ResponseInnerParametersInner {
	this := IserverContractConidAlgosGet200ResponseInnerParametersInner{}
	return &this
}

// GetId returns the Id field value
func (o *IserverContractConidAlgosGet200ResponseInnerParametersInner) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *IserverContractConidAlgosGet200ResponseInnerParametersInner) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *IserverContractConidAlgosGet200ResponseInnerParametersInner) SetId(v string) {
	o.Id = v
}

// GetRequired returns the Required field value if set, zero value otherwise.
func (o *IserverContractConidAlgosGet200ResponseInnerParametersInner) GetRequired() bool {
	if o == nil || IsNil(o.Required) {
		var ret bool
		return ret
	}
	return *o.Required
}

// GetRequiredOk returns a tuple with the Required field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *IserverContractConidAlgosGet200ResponseInnerParametersInner) GetRequiredOk() (*bool, bool) {
	if o == nil || IsNil(o.Required) {
		return nil, false
	}
	return o.Required, true
}

// HasRequired returns a boolean if a field has been set.
func (o *IserverContractConidAlgosGet200ResponseInnerParametersInner) HasRequired() bool {
	if o != nil && !IsNil(o.Required) {
		return true
	}

	return false
}

// SetRequired gets a reference to the given bool and assigns it to the Required field.
func (o *IserverContractConidAlgosGet200ResponseInnerParametersInner) SetRequired(v bool) {
	o.Required = &v
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *IserverContractConidAlgosGet200ResponseInnerParametersInner) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *IserverContractConidAlgosGet200ResponseInnerParametersInner) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *IserverContractConidAlgosGet200ResponseInnerParametersInner) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *IserverContractConidAlgosGet200ResponseInnerParametersInner) SetName(v string) {
	o.Name = &v
}

// GetValueClassName returns the ValueClassName field value
func (o *IserverContractConidAlgosGet200ResponseInnerParametersInner) GetValueClassName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ValueClassName
}

// GetValueClassNameOk returns a tuple with the ValueClassName field value
// and a boolean to check if the value has been set.
func (o *IserverContractConidAlgosGet200ResponseInnerParametersInner) GetValueClassNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ValueClassName, true
}

// SetValueClassName sets field value
func (o *IserverContractConidAlgosGet200ResponseInnerParametersInner) SetValueClassName(v string) {
	o.ValueClassName = v
}

// GetMinValue returns the MinValue field value if set, zero value otherwise.
func (o *IserverContractConidAlgosGet200ResponseInnerParametersInner) GetMinValue() float32 {
	if o == nil || IsNil(o.MinValue) {
		var ret float32
		return ret
	}
	return *o.MinValue
}

// GetMinValueOk returns a tuple with the MinValue field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *IserverContractConidAlgosGet200ResponseInnerParametersInner) GetMinValueOk() (*float32, bool) {
	if o == nil || IsNil(o.MinValue) {
		return nil, false
	}
	return o.MinValue, true
}

// HasMinValue returns a boolean if a field has been set.
func (o *IserverContractConidAlgosGet200ResponseInnerParametersInner) HasMinValue() bool {
	if o != nil && !IsNil(o.MinValue) {
		return true
	}

	return false
}

// SetMinValue gets a reference to the given float32 and assigns it to the MinValue field.
func (o *IserverContractConidAlgosGet200ResponseInnerParametersInner) SetMinValue(v float32) {
	o.MinValue = &v
}

// GetMaxValue returns the MaxValue field value if set, zero value otherwise.
func (o *IserverContractConidAlgosGet200ResponseInnerParametersInner) GetMaxValue() float32 {
	if o == nil || IsNil(o.MaxValue) {
		var ret float32
		return ret
	}
	return *o.MaxValue
}

// GetMaxValueOk returns a tuple with the MaxValue field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *IserverContractConidAlgosGet200ResponseInnerParametersInner) GetMaxValueOk() (*float32, bool) {
	if o == nil || IsNil(o.MaxValue) {
		return nil, false
	}
	return o.MaxValue, true
}

// HasMaxValue returns a boolean if a field has been set.
func (o *IserverContractConidAlgosGet200ResponseInnerParametersInner) HasMaxValue() bool {
	if o != nil && !IsNil(o.MaxValue) {
		return true
	}

	return false
}

// SetMaxValue gets a reference to the given float32 and assigns it to the MaxValue field.
func (o *IserverContractConidAlgosGet200ResponseInnerParametersInner) SetMaxValue(v float32) {
	o.MaxValue = &v
}

// GetDefaultValue returns the DefaultValue field value if set, zero value otherwise.
func (o *IserverContractConidAlgosGet200ResponseInnerParametersInner) GetDefaultValue() bool {
	if o == nil || IsNil(o.DefaultValue) {
		var ret bool
		return ret
	}
	return *o.DefaultValue
}

// GetDefaultValueOk returns a tuple with the DefaultValue field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *IserverContractConidAlgosGet200ResponseInnerParametersInner) GetDefaultValueOk() (*bool, bool) {
	if o == nil || IsNil(o.DefaultValue) {
		return nil, false
	}
	return o.DefaultValue, true
}

// HasDefaultValue returns a boolean if a field has been set.
func (o *IserverContractConidAlgosGet200ResponseInnerParametersInner) HasDefaultValue() bool {
	if o != nil && !IsNil(o.DefaultValue) {
		return true
	}

	return false
}

// SetDefaultValue gets a reference to the given bool and assigns it to the DefaultValue field.
func (o *IserverContractConidAlgosGet200ResponseInnerParametersInner) SetDefaultValue(v bool) {
	o.DefaultValue = &v
}

// GetLegalStrings returns the LegalStrings field value if set, zero value otherwise.
func (o *IserverContractConidAlgosGet200ResponseInnerParametersInner) GetLegalStrings() string {
	if o == nil || IsNil(o.LegalStrings) {
		var ret string
		return ret
	}
	return *o.LegalStrings
}

// GetLegalStringsOk returns a tuple with the LegalStrings field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *IserverContractConidAlgosGet200ResponseInnerParametersInner) GetLegalStringsOk() (*string, bool) {
	if o == nil || IsNil(o.LegalStrings) {
		return nil, false
	}
	return o.LegalStrings, true
}

// HasLegalStrings returns a boolean if a field has been set.
func (o *IserverContractConidAlgosGet200ResponseInnerParametersInner) HasLegalStrings() bool {
	if o != nil && !IsNil(o.LegalStrings) {
		return true
	}

	return false
}

// SetLegalStrings gets a reference to the given string and assigns it to the LegalStrings field.
func (o *IserverContractConidAlgosGet200ResponseInnerParametersInner) SetLegalStrings(v string) {
	o.LegalStrings = &v
}

// GetDescription returns the Description field value if set, zero value otherwise.
func (o *IserverContractConidAlgosGet200ResponseInnerParametersInner) GetDescription() string {
	if o == nil || IsNil(o.Description) {
		var ret string
		return ret
	}
	return *o.Description
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *IserverContractConidAlgosGet200ResponseInnerParametersInner) GetDescriptionOk() (*string, bool) {
	if o == nil || IsNil(o.Description) {
		return nil, false
	}
	return o.Description, true
}

// HasDescription returns a boolean if a field has been set.
func (o *IserverContractConidAlgosGet200ResponseInnerParametersInner) HasDescription() bool {
	if o != nil && !IsNil(o.Description) {
		return true
	}

	return false
}

// SetDescription gets a reference to the given string and assigns it to the Description field.
func (o *IserverContractConidAlgosGet200ResponseInnerParametersInner) SetDescription(v string) {
	o.Description = &v
}

// GetGuiRank returns the GuiRank field value if set, zero value otherwise.
func (o *IserverContractConidAlgosGet200ResponseInnerParametersInner) GetGuiRank() float32 {
	if o == nil || IsNil(o.GuiRank) {
		var ret float32
		return ret
	}
	return *o.GuiRank
}

// GetGuiRankOk returns a tuple with the GuiRank field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *IserverContractConidAlgosGet200ResponseInnerParametersInner) GetGuiRankOk() (*float32, bool) {
	if o == nil || IsNil(o.GuiRank) {
		return nil, false
	}
	return o.GuiRank, true
}

// HasGuiRank returns a boolean if a field has been set.
func (o *IserverContractConidAlgosGet200ResponseInnerParametersInner) HasGuiRank() bool {
	if o != nil && !IsNil(o.GuiRank) {
		return true
	}

	return false
}

// SetGuiRank gets a reference to the given float32 and assigns it to the GuiRank field.
func (o *IserverContractConidAlgosGet200ResponseInnerParametersInner) SetGuiRank(v float32) {
	o.GuiRank = &v
}

// GetPriceMarketRule returns the PriceMarketRule field value if set, zero value otherwise.
func (o *IserverContractConidAlgosGet200ResponseInnerParametersInner) GetPriceMarketRule() bool {
	if o == nil || IsNil(o.PriceMarketRule) {
		var ret bool
		return ret
	}
	return *o.PriceMarketRule
}

// GetPriceMarketRuleOk returns a tuple with the PriceMarketRule field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *IserverContractConidAlgosGet200ResponseInnerParametersInner) GetPriceMarketRuleOk() (*bool, bool) {
	if o == nil || IsNil(o.PriceMarketRule) {
		return nil, false
	}
	return o.PriceMarketRule, true
}

// HasPriceMarketRule returns a boolean if a field has been set.
func (o *IserverContractConidAlgosGet200ResponseInnerParametersInner) HasPriceMarketRule() bool {
	if o != nil && !IsNil(o.PriceMarketRule) {
		return true
	}

	return false
}

// SetPriceMarketRule gets a reference to the given bool and assigns it to the PriceMarketRule field.
func (o *IserverContractConidAlgosGet200ResponseInnerParametersInner) SetPriceMarketRule(v bool) {
	o.PriceMarketRule = &v
}

// GetEnabledConditions returns the EnabledConditions field value if set, zero value otherwise.
func (o *IserverContractConidAlgosGet200ResponseInnerParametersInner) GetEnabledConditions() string {
	if o == nil || IsNil(o.EnabledConditions) {
		var ret string
		return ret
	}
	return *o.EnabledConditions
}

// GetEnabledConditionsOk returns a tuple with the EnabledConditions field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *IserverContractConidAlgosGet200ResponseInnerParametersInner) GetEnabledConditionsOk() (*string, bool) {
	if o == nil || IsNil(o.EnabledConditions) {
		return nil, false
	}
	return o.EnabledConditions, true
}

// HasEnabledConditions returns a boolean if a field has been set.
func (o *IserverContractConidAlgosGet200ResponseInnerParametersInner) HasEnabledConditions() bool {
	if o != nil && !IsNil(o.EnabledConditions) {
		return true
	}

	return false
}

// SetEnabledConditions gets a reference to the given string and assigns it to the EnabledConditions field.
func (o *IserverContractConidAlgosGet200ResponseInnerParametersInner) SetEnabledConditions(v string) {
	o.EnabledConditions = &v
}

func (o IserverContractConidAlgosGet200ResponseInnerParametersInner) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o IserverContractConidAlgosGet200ResponseInnerParametersInner) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	if !IsNil(o.Required) {
		toSerialize["required"] = o.Required
	}
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	toSerialize["valueClassName"] = o.ValueClassName
	if !IsNil(o.MinValue) {
		toSerialize["minValue"] = o.MinValue
	}
	if !IsNil(o.MaxValue) {
		toSerialize["maxValue"] = o.MaxValue
	}
	if !IsNil(o.DefaultValue) {
		toSerialize["defaultValue"] = o.DefaultValue
	}
	if !IsNil(o.LegalStrings) {
		toSerialize["legalStrings"] = o.LegalStrings
	}
	if !IsNil(o.Description) {
		toSerialize["description"] = o.Description
	}
	if !IsNil(o.GuiRank) {
		toSerialize["guiRank"] = o.GuiRank
	}
	if !IsNil(o.PriceMarketRule) {
		toSerialize["priceMarketRule"] = o.PriceMarketRule
	}
	if !IsNil(o.EnabledConditions) {
		toSerialize["enabledConditions"] = o.EnabledConditions
	}
	return toSerialize, nil
}

func (o *IserverContractConidAlgosGet200ResponseInnerParametersInner) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
		"valueClassName",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varIserverContractConidAlgosGet200ResponseInnerParametersInner := _IserverContractConidAlgosGet200ResponseInnerParametersInner{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varIserverContractConidAlgosGet200ResponseInnerParametersInner)

	if err != nil {
		return err
	}

	*o = IserverContractConidAlgosGet200ResponseInnerParametersInner(varIserverContractConidAlgosGet200ResponseInnerParametersInner)

	return err
}

type NullableIserverContractConidAlgosGet200ResponseInnerParametersInner struct {
	value *IserverContractConidAlgosGet200ResponseInnerParametersInner
	isSet bool
}

func (v NullableIserverContractConidAlgosGet200ResponseInnerParametersInner) Get() *IserverContractConidAlgosGet200ResponseInnerParametersInner {
	return v.value
}

func (v *NullableIserverContractConidAlgosGet200ResponseInnerParametersInner) Set(val *IserverContractConidAlgosGet200ResponseInnerParametersInner) {
	v.value = val
	v.isSet = true
}

func (v NullableIserverContractConidAlgosGet200ResponseInnerParametersInner) IsSet() bool {
	return v.isSet
}

func (v *NullableIserverContractConidAlgosGet200ResponseInnerParametersInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableIserverContractConidAlgosGet200ResponseInnerParametersInner(val *IserverContractConidAlgosGet200ResponseInnerParametersInner) *NullableIserverContractConidAlgosGet200ResponseInnerParametersInner {
	return &NullableIserverContractConidAlgosGet200ResponseInnerParametersInner{value: val, isSet: true}
}

func (v NullableIserverContractConidAlgosGet200ResponseInnerParametersInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableIserverContractConidAlgosGet200ResponseInnerParametersInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
