/*
Client Portal Web API

Client Poral Web API

API version: 1.0.0
Contact: e@e.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

import (
	"encoding/json"
)

// checks if the GetFutures500Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetFutures500Response{}

// GetFutures500Response struct for GetFutures500Response
type GetFutures500Response struct {
	Error *string `json:"error,omitempty"`
}

// NewGetFutures500Response instantiates a new GetFutures500Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetFutures500Response() *GetFutures500Response {
	this := GetFutures500Response{}
	return &this
}

// NewGetFutures500ResponseWithDefaults instantiates a new GetFutures500Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetFutures500ResponseWithDefaults() *GetFutures500Response {
	this := GetFutures500Response{}
	return &this
}

// GetError returns the Error field value if set, zero value otherwise.
func (o *GetFutures500Response) GetError() string {
	if o == nil || IsNil(o.Error) {
		var ret string
		return ret
	}
	return *o.Error
}

// GetErrorOk returns a tuple with the Error field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetFutures500Response) GetErrorOk() (*string, bool) {
	if o == nil || IsNil(o.Error) {
		return nil, false
	}
	return o.Error, true
}

// HasError returns a boolean if a field has been set.
func (o *GetFutures500Response) HasError() bool {
	if o != nil && !IsNil(o.Error) {
		return true
	}

	return false
}

// SetError gets a reference to the given string and assigns it to the Error field.
func (o *GetFutures500Response) SetError(v string) {
	o.Error = &v
}

func (o GetFutures500Response) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetFutures500Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Error) {
		toSerialize["error"] = o.Error
	}
	return toSerialize, nil
}

type NullableGetFutures500Response struct {
	value *GetFutures500Response
	isSet bool
}

func (v NullableGetFutures500Response) Get() *GetFutures500Response {
	return v.value
}

func (v *NullableGetFutures500Response) Set(val *GetFutures500Response) {
	v.value = val
	v.isSet = true
}

func (v NullableGetFutures500Response) IsSet() bool {
	return v.isSet
}

func (v *NullableGetFutures500Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetFutures500Response(val *GetFutures500Response) *NullableGetFutures500Response {
	return &NullableGetFutures500Response{value: val, isSet: true}
}

func (v NullableGetFutures500Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetFutures500Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
