/*
Client Portal Web API

Client Poral Web API

API version: 1.0.0
Contact: e@e.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

import (
	"encoding/json"
)

// checks if the IserverContractRulesPost200Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &IserverContractRulesPost200Response{}

// IserverContractRulesPost200Response struct for IserverContractRulesPost200Response
type IserverContractRulesPost200Response struct {
	Rules []IserverContractRulesPost200ResponseRulesInner `json:"rules,omitempty"`
}

// NewIserverContractRulesPost200Response instantiates a new IserverContractRulesPost200Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewIserverContractRulesPost200Response() *IserverContractRulesPost200Response {
	this := IserverContractRulesPost200Response{}
	return &this
}

// NewIserverContractRulesPost200ResponseWithDefaults instantiates a new IserverContractRulesPost200Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewIserverContractRulesPost200ResponseWithDefaults() *IserverContractRulesPost200Response {
	this := IserverContractRulesPost200Response{}
	return &this
}

// GetRules returns the Rules field value if set, zero value otherwise.
func (o *IserverContractRulesPost200Response) GetRules() []IserverContractRulesPost200ResponseRulesInner {
	if o == nil || IsNil(o.Rules) {
		var ret []IserverContractRulesPost200ResponseRulesInner
		return ret
	}
	return o.Rules
}

// GetRulesOk returns a tuple with the Rules field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *IserverContractRulesPost200Response) GetRulesOk() ([]IserverContractRulesPost200ResponseRulesInner, bool) {
	if o == nil || IsNil(o.Rules) {
		return nil, false
	}
	return o.Rules, true
}

// HasRules returns a boolean if a field has been set.
func (o *IserverContractRulesPost200Response) HasRules() bool {
	if o != nil && !IsNil(o.Rules) {
		return true
	}

	return false
}

// SetRules gets a reference to the given []IserverContractRulesPost200ResponseRulesInner and assigns it to the Rules field.
func (o *IserverContractRulesPost200Response) SetRules(v []IserverContractRulesPost200ResponseRulesInner) {
	o.Rules = v
}

func (o IserverContractRulesPost200Response) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o IserverContractRulesPost200Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Rules) {
		toSerialize["rules"] = o.Rules
	}
	return toSerialize, nil
}

type NullableIserverContractRulesPost200Response struct {
	value *IserverContractRulesPost200Response
	isSet bool
}

func (v NullableIserverContractRulesPost200Response) Get() *IserverContractRulesPost200Response {
	return v.value
}

func (v *NullableIserverContractRulesPost200Response) Set(val *IserverContractRulesPost200Response) {
	v.value = val
	v.isSet = true
}

func (v NullableIserverContractRulesPost200Response) IsSet() bool {
	return v.isSet
}

func (v *NullableIserverContractRulesPost200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableIserverContractRulesPost200Response(val *IserverContractRulesPost200Response) *NullableIserverContractRulesPost200Response {
	return &NullableIserverContractRulesPost200Response{value: val, isSet: true}
}

func (v NullableIserverContractRulesPost200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableIserverContractRulesPost200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
