/*
Client Portal Web API

Client Poral Web API

API version: 1.0.0
Contact: e@e.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

import (
	"encoding/json"
)

// checks if the GetCCPAccount200Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetCCPAccount200Response{}

// GetCCPAccount200Response struct for GetCCPAccount200Response
type GetCCPAccount200Response struct {
	// The primary or parent account.
	MainAcct *string `json:"mainAcct,omitempty"`
	// List of tradeable or Sub Accounts
	AcctList []GetCCPAccount200ResponseAcctListInner `json:"acctList,omitempty"`
}

// NewGetCCPAccount200Response instantiates a new GetCCPAccount200Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetCCPAccount200Response() *GetCCPAccount200Response {
	this := GetCCPAccount200Response{}
	return &this
}

// NewGetCCPAccount200ResponseWithDefaults instantiates a new GetCCPAccount200Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetCCPAccount200ResponseWithDefaults() *GetCCPAccount200Response {
	this := GetCCPAccount200Response{}
	return &this
}

// GetMainAcct returns the MainAcct field value if set, zero value otherwise.
func (o *GetCCPAccount200Response) GetMainAcct() string {
	if o == nil || IsNil(o.MainAcct) {
		var ret string
		return ret
	}
	return *o.MainAcct
}

// GetMainAcctOk returns a tuple with the MainAcct field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetCCPAccount200Response) GetMainAcctOk() (*string, bool) {
	if o == nil || IsNil(o.MainAcct) {
		return nil, false
	}
	return o.MainAcct, true
}

// HasMainAcct returns a boolean if a field has been set.
func (o *GetCCPAccount200Response) HasMainAcct() bool {
	if o != nil && !IsNil(o.MainAcct) {
		return true
	}

	return false
}

// SetMainAcct gets a reference to the given string and assigns it to the MainAcct field.
func (o *GetCCPAccount200Response) SetMainAcct(v string) {
	o.MainAcct = &v
}

// GetAcctList returns the AcctList field value if set, zero value otherwise.
func (o *GetCCPAccount200Response) GetAcctList() []GetCCPAccount200ResponseAcctListInner {
	if o == nil || IsNil(o.AcctList) {
		var ret []GetCCPAccount200ResponseAcctListInner
		return ret
	}
	return o.AcctList
}

// GetAcctListOk returns a tuple with the AcctList field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetCCPAccount200Response) GetAcctListOk() ([]GetCCPAccount200ResponseAcctListInner, bool) {
	if o == nil || IsNil(o.AcctList) {
		return nil, false
	}
	return o.AcctList, true
}

// HasAcctList returns a boolean if a field has been set.
func (o *GetCCPAccount200Response) HasAcctList() bool {
	if o != nil && !IsNil(o.AcctList) {
		return true
	}

	return false
}

// SetAcctList gets a reference to the given []GetCCPAccount200ResponseAcctListInner and assigns it to the AcctList field.
func (o *GetCCPAccount200Response) SetAcctList(v []GetCCPAccount200ResponseAcctListInner) {
	o.AcctList = v
}

func (o GetCCPAccount200Response) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetCCPAccount200Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.MainAcct) {
		toSerialize["mainAcct"] = o.MainAcct
	}
	if !IsNil(o.AcctList) {
		toSerialize["acctList"] = o.AcctList
	}
	return toSerialize, nil
}

type NullableGetCCPAccount200Response struct {
	value *GetCCPAccount200Response
	isSet bool
}

func (v NullableGetCCPAccount200Response) Get() *GetCCPAccount200Response {
	return v.value
}

func (v *NullableGetCCPAccount200Response) Set(val *GetCCPAccount200Response) {
	v.value = val
	v.isSet = true
}

func (v NullableGetCCPAccount200Response) IsSet() bool {
	return v.isSet
}

func (v *NullableGetCCPAccount200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetCCPAccount200Response(val *GetCCPAccount200Response) *NullableGetCCPAccount200Response {
	return &NullableGetCCPAccount200Response{value: val, isSet: true}
}

func (v NullableGetCCPAccount200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetCCPAccount200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
