/*
Client Portal Web API

Client Poral Web API

API version: 1.0.0
Contact: e@e.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

import (
	"encoding/json"
)

// checks if the GetLiveOrders200ResponseOrdersInner type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetLiveOrders200ResponseOrdersInner{}

// GetLiveOrders200ResponseOrdersInner struct for GetLiveOrders200ResponseOrdersInner
type GetLiveOrders200ResponseOrdersInner struct {
	// Account number
	Acct *string `json:"acct,omitempty"`
	// conid and exchange. Format supports conid or conid@exchange
	Conidex *string `json:"conidex,omitempty"`
	// Contract identifier
	Conid *float32 `json:"conid,omitempty"`
	// Order identifier
	OrderId *string `json:"orderId,omitempty"`
	// Cash currency
	CashCcy *string `json:"cashCcy,omitempty"`
	// Quantity outstanding and total quantity concatenated with forward slash separator
	SizeAndFills *string `json:"sizeAndFills,omitempty"`
	// Order description
	OrderDesc *string `json:"orderDesc,omitempty"`
	// Formatted ticker description
	Description1 *string `json:"description1,omitempty"`
	// Underlying symbol
	Ticker *string `json:"ticker,omitempty"`
	// Asset class
	SecType *string `json:"secType,omitempty"`
	// Listing Exchange
	ListingExchange *string `json:"listingExchange,omitempty"`
	// Quantity remaining
	RemainingQuantity *float32 `json:"remainingQuantity,omitempty"`
	// Quantity filled
	FilledQuantity *float32 `json:"filledQuantity,omitempty"`
	// Company Name
	CompanyName *string `json:"companyName,omitempty"`
	// Status of the order
	Status *string `json:"status,omitempty"`
	// Original order type
	OrigOrderType *string `json:"origOrderType,omitempty"`
	// Supports Tax Optimization with 0 for no and 1 for yes
	SupportsTaxOpt *float32 `json:"supportsTaxOpt,omitempty"`
	// Last status update in format YYMMDDhhmms based in GMT
	LastExecutionTime *float32 `json:"lastExecutionTime,omitempty"`
	// Last status update unix time in ms
	LastExecutionTimeR *float32 `json:"lastExecutionTime_r,omitempty"`
	// Order type
	OrderType *string `json:"orderType,omitempty"`
	// Order reference
	OrderRef *string `json:"order_ref,omitempty"`
	// The side of the market of the order.  * BUY: Buy contract near posted ask price  * SELL: Sell contract near posted bid price  * ASSN: Option Assignment, if BUYSELL=BUY and OptionType=PUT or BUYSELL=SELL and OptionType=CALL  * EXER: Option Exercise, if BUYSELL=SELL and OptionType=PUT or BUYSELL=BUY and OptionType=CALL
	Side *string `json:"side,omitempty"`
	// Time in force
	TimeInForce *string `json:"timeInForce,omitempty"`
	// Price of order
	Price *float32 `json:"price,omitempty"`
	// Background color in hex format
	BgColor *string `json:"bgColor,omitempty"`
	// Foreground color in hex format
	FgColor *string `json:"fgColor,omitempty"`
}

// NewGetLiveOrders200ResponseOrdersInner instantiates a new GetLiveOrders200ResponseOrdersInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetLiveOrders200ResponseOrdersInner() *GetLiveOrders200ResponseOrdersInner {
	this := GetLiveOrders200ResponseOrdersInner{}
	return &this
}

// NewGetLiveOrders200ResponseOrdersInnerWithDefaults instantiates a new GetLiveOrders200ResponseOrdersInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetLiveOrders200ResponseOrdersInnerWithDefaults() *GetLiveOrders200ResponseOrdersInner {
	this := GetLiveOrders200ResponseOrdersInner{}
	return &this
}

// GetAcct returns the Acct field value if set, zero value otherwise.
func (o *GetLiveOrders200ResponseOrdersInner) GetAcct() string {
	if o == nil || IsNil(o.Acct) {
		var ret string
		return ret
	}
	return *o.Acct
}

// GetAcctOk returns a tuple with the Acct field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetLiveOrders200ResponseOrdersInner) GetAcctOk() (*string, bool) {
	if o == nil || IsNil(o.Acct) {
		return nil, false
	}
	return o.Acct, true
}

// HasAcct returns a boolean if a field has been set.
func (o *GetLiveOrders200ResponseOrdersInner) HasAcct() bool {
	if o != nil && !IsNil(o.Acct) {
		return true
	}

	return false
}

// SetAcct gets a reference to the given string and assigns it to the Acct field.
func (o *GetLiveOrders200ResponseOrdersInner) SetAcct(v string) {
	o.Acct = &v
}

// GetConidex returns the Conidex field value if set, zero value otherwise.
func (o *GetLiveOrders200ResponseOrdersInner) GetConidex() string {
	if o == nil || IsNil(o.Conidex) {
		var ret string
		return ret
	}
	return *o.Conidex
}

// GetConidexOk returns a tuple with the Conidex field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetLiveOrders200ResponseOrdersInner) GetConidexOk() (*string, bool) {
	if o == nil || IsNil(o.Conidex) {
		return nil, false
	}
	return o.Conidex, true
}

// HasConidex returns a boolean if a field has been set.
func (o *GetLiveOrders200ResponseOrdersInner) HasConidex() bool {
	if o != nil && !IsNil(o.Conidex) {
		return true
	}

	return false
}

// SetConidex gets a reference to the given string and assigns it to the Conidex field.
func (o *GetLiveOrders200ResponseOrdersInner) SetConidex(v string) {
	o.Conidex = &v
}

// GetConid returns the Conid field value if set, zero value otherwise.
func (o *GetLiveOrders200ResponseOrdersInner) GetConid() float32 {
	if o == nil || IsNil(o.Conid) {
		var ret float32
		return ret
	}
	return *o.Conid
}

// GetConidOk returns a tuple with the Conid field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetLiveOrders200ResponseOrdersInner) GetConidOk() (*float32, bool) {
	if o == nil || IsNil(o.Conid) {
		return nil, false
	}
	return o.Conid, true
}

// HasConid returns a boolean if a field has been set.
func (o *GetLiveOrders200ResponseOrdersInner) HasConid() bool {
	if o != nil && !IsNil(o.Conid) {
		return true
	}

	return false
}

// SetConid gets a reference to the given float32 and assigns it to the Conid field.
func (o *GetLiveOrders200ResponseOrdersInner) SetConid(v float32) {
	o.Conid = &v
}

// GetOrderId returns the OrderId field value if set, zero value otherwise.
func (o *GetLiveOrders200ResponseOrdersInner) GetOrderId() string {
	if o == nil || IsNil(o.OrderId) {
		var ret string
		return ret
	}
	return *o.OrderId
}

// GetOrderIdOk returns a tuple with the OrderId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetLiveOrders200ResponseOrdersInner) GetOrderIdOk() (*string, bool) {
	if o == nil || IsNil(o.OrderId) {
		return nil, false
	}
	return o.OrderId, true
}

// HasOrderId returns a boolean if a field has been set.
func (o *GetLiveOrders200ResponseOrdersInner) HasOrderId() bool {
	if o != nil && !IsNil(o.OrderId) {
		return true
	}

	return false
}

// SetOrderId gets a reference to the given string and assigns it to the OrderId field.
func (o *GetLiveOrders200ResponseOrdersInner) SetOrderId(v string) {
	o.OrderId = &v
}

// GetCashCcy returns the CashCcy field value if set, zero value otherwise.
func (o *GetLiveOrders200ResponseOrdersInner) GetCashCcy() string {
	if o == nil || IsNil(o.CashCcy) {
		var ret string
		return ret
	}
	return *o.CashCcy
}

// GetCashCcyOk returns a tuple with the CashCcy field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetLiveOrders200ResponseOrdersInner) GetCashCcyOk() (*string, bool) {
	if o == nil || IsNil(o.CashCcy) {
		return nil, false
	}
	return o.CashCcy, true
}

// HasCashCcy returns a boolean if a field has been set.
func (o *GetLiveOrders200ResponseOrdersInner) HasCashCcy() bool {
	if o != nil && !IsNil(o.CashCcy) {
		return true
	}

	return false
}

// SetCashCcy gets a reference to the given string and assigns it to the CashCcy field.
func (o *GetLiveOrders200ResponseOrdersInner) SetCashCcy(v string) {
	o.CashCcy = &v
}

// GetSizeAndFills returns the SizeAndFills field value if set, zero value otherwise.
func (o *GetLiveOrders200ResponseOrdersInner) GetSizeAndFills() string {
	if o == nil || IsNil(o.SizeAndFills) {
		var ret string
		return ret
	}
	return *o.SizeAndFills
}

// GetSizeAndFillsOk returns a tuple with the SizeAndFills field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetLiveOrders200ResponseOrdersInner) GetSizeAndFillsOk() (*string, bool) {
	if o == nil || IsNil(o.SizeAndFills) {
		return nil, false
	}
	return o.SizeAndFills, true
}

// HasSizeAndFills returns a boolean if a field has been set.
func (o *GetLiveOrders200ResponseOrdersInner) HasSizeAndFills() bool {
	if o != nil && !IsNil(o.SizeAndFills) {
		return true
	}

	return false
}

// SetSizeAndFills gets a reference to the given string and assigns it to the SizeAndFills field.
func (o *GetLiveOrders200ResponseOrdersInner) SetSizeAndFills(v string) {
	o.SizeAndFills = &v
}

// GetOrderDesc returns the OrderDesc field value if set, zero value otherwise.
func (o *GetLiveOrders200ResponseOrdersInner) GetOrderDesc() string {
	if o == nil || IsNil(o.OrderDesc) {
		var ret string
		return ret
	}
	return *o.OrderDesc
}

// GetOrderDescOk returns a tuple with the OrderDesc field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetLiveOrders200ResponseOrdersInner) GetOrderDescOk() (*string, bool) {
	if o == nil || IsNil(o.OrderDesc) {
		return nil, false
	}
	return o.OrderDesc, true
}

// HasOrderDesc returns a boolean if a field has been set.
func (o *GetLiveOrders200ResponseOrdersInner) HasOrderDesc() bool {
	if o != nil && !IsNil(o.OrderDesc) {
		return true
	}

	return false
}

// SetOrderDesc gets a reference to the given string and assigns it to the OrderDesc field.
func (o *GetLiveOrders200ResponseOrdersInner) SetOrderDesc(v string) {
	o.OrderDesc = &v
}

// GetDescription1 returns the Description1 field value if set, zero value otherwise.
func (o *GetLiveOrders200ResponseOrdersInner) GetDescription1() string {
	if o == nil || IsNil(o.Description1) {
		var ret string
		return ret
	}
	return *o.Description1
}

// GetDescription1Ok returns a tuple with the Description1 field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetLiveOrders200ResponseOrdersInner) GetDescription1Ok() (*string, bool) {
	if o == nil || IsNil(o.Description1) {
		return nil, false
	}
	return o.Description1, true
}

// HasDescription1 returns a boolean if a field has been set.
func (o *GetLiveOrders200ResponseOrdersInner) HasDescription1() bool {
	if o != nil && !IsNil(o.Description1) {
		return true
	}

	return false
}

// SetDescription1 gets a reference to the given string and assigns it to the Description1 field.
func (o *GetLiveOrders200ResponseOrdersInner) SetDescription1(v string) {
	o.Description1 = &v
}

// GetTicker returns the Ticker field value if set, zero value otherwise.
func (o *GetLiveOrders200ResponseOrdersInner) GetTicker() string {
	if o == nil || IsNil(o.Ticker) {
		var ret string
		return ret
	}
	return *o.Ticker
}

// GetTickerOk returns a tuple with the Ticker field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetLiveOrders200ResponseOrdersInner) GetTickerOk() (*string, bool) {
	if o == nil || IsNil(o.Ticker) {
		return nil, false
	}
	return o.Ticker, true
}

// HasTicker returns a boolean if a field has been set.
func (o *GetLiveOrders200ResponseOrdersInner) HasTicker() bool {
	if o != nil && !IsNil(o.Ticker) {
		return true
	}

	return false
}

// SetTicker gets a reference to the given string and assigns it to the Ticker field.
func (o *GetLiveOrders200ResponseOrdersInner) SetTicker(v string) {
	o.Ticker = &v
}

// GetSecType returns the SecType field value if set, zero value otherwise.
func (o *GetLiveOrders200ResponseOrdersInner) GetSecType() string {
	if o == nil || IsNil(o.SecType) {
		var ret string
		return ret
	}
	return *o.SecType
}

// GetSecTypeOk returns a tuple with the SecType field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetLiveOrders200ResponseOrdersInner) GetSecTypeOk() (*string, bool) {
	if o == nil || IsNil(o.SecType) {
		return nil, false
	}
	return o.SecType, true
}

// HasSecType returns a boolean if a field has been set.
func (o *GetLiveOrders200ResponseOrdersInner) HasSecType() bool {
	if o != nil && !IsNil(o.SecType) {
		return true
	}

	return false
}

// SetSecType gets a reference to the given string and assigns it to the SecType field.
func (o *GetLiveOrders200ResponseOrdersInner) SetSecType(v string) {
	o.SecType = &v
}

// GetListingExchange returns the ListingExchange field value if set, zero value otherwise.
func (o *GetLiveOrders200ResponseOrdersInner) GetListingExchange() string {
	if o == nil || IsNil(o.ListingExchange) {
		var ret string
		return ret
	}
	return *o.ListingExchange
}

// GetListingExchangeOk returns a tuple with the ListingExchange field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetLiveOrders200ResponseOrdersInner) GetListingExchangeOk() (*string, bool) {
	if o == nil || IsNil(o.ListingExchange) {
		return nil, false
	}
	return o.ListingExchange, true
}

// HasListingExchange returns a boolean if a field has been set.
func (o *GetLiveOrders200ResponseOrdersInner) HasListingExchange() bool {
	if o != nil && !IsNil(o.ListingExchange) {
		return true
	}

	return false
}

// SetListingExchange gets a reference to the given string and assigns it to the ListingExchange field.
func (o *GetLiveOrders200ResponseOrdersInner) SetListingExchange(v string) {
	o.ListingExchange = &v
}

// GetRemainingQuantity returns the RemainingQuantity field value if set, zero value otherwise.
func (o *GetLiveOrders200ResponseOrdersInner) GetRemainingQuantity() float32 {
	if o == nil || IsNil(o.RemainingQuantity) {
		var ret float32
		return ret
	}
	return *o.RemainingQuantity
}

// GetRemainingQuantityOk returns a tuple with the RemainingQuantity field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetLiveOrders200ResponseOrdersInner) GetRemainingQuantityOk() (*float32, bool) {
	if o == nil || IsNil(o.RemainingQuantity) {
		return nil, false
	}
	return o.RemainingQuantity, true
}

// HasRemainingQuantity returns a boolean if a field has been set.
func (o *GetLiveOrders200ResponseOrdersInner) HasRemainingQuantity() bool {
	if o != nil && !IsNil(o.RemainingQuantity) {
		return true
	}

	return false
}

// SetRemainingQuantity gets a reference to the given float32 and assigns it to the RemainingQuantity field.
func (o *GetLiveOrders200ResponseOrdersInner) SetRemainingQuantity(v float32) {
	o.RemainingQuantity = &v
}

// GetFilledQuantity returns the FilledQuantity field value if set, zero value otherwise.
func (o *GetLiveOrders200ResponseOrdersInner) GetFilledQuantity() float32 {
	if o == nil || IsNil(o.FilledQuantity) {
		var ret float32
		return ret
	}
	return *o.FilledQuantity
}

// GetFilledQuantityOk returns a tuple with the FilledQuantity field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetLiveOrders200ResponseOrdersInner) GetFilledQuantityOk() (*float32, bool) {
	if o == nil || IsNil(o.FilledQuantity) {
		return nil, false
	}
	return o.FilledQuantity, true
}

// HasFilledQuantity returns a boolean if a field has been set.
func (o *GetLiveOrders200ResponseOrdersInner) HasFilledQuantity() bool {
	if o != nil && !IsNil(o.FilledQuantity) {
		return true
	}

	return false
}

// SetFilledQuantity gets a reference to the given float32 and assigns it to the FilledQuantity field.
func (o *GetLiveOrders200ResponseOrdersInner) SetFilledQuantity(v float32) {
	o.FilledQuantity = &v
}

// GetCompanyName returns the CompanyName field value if set, zero value otherwise.
func (o *GetLiveOrders200ResponseOrdersInner) GetCompanyName() string {
	if o == nil || IsNil(o.CompanyName) {
		var ret string
		return ret
	}
	return *o.CompanyName
}

// GetCompanyNameOk returns a tuple with the CompanyName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetLiveOrders200ResponseOrdersInner) GetCompanyNameOk() (*string, bool) {
	if o == nil || IsNil(o.CompanyName) {
		return nil, false
	}
	return o.CompanyName, true
}

// HasCompanyName returns a boolean if a field has been set.
func (o *GetLiveOrders200ResponseOrdersInner) HasCompanyName() bool {
	if o != nil && !IsNil(o.CompanyName) {
		return true
	}

	return false
}

// SetCompanyName gets a reference to the given string and assigns it to the CompanyName field.
func (o *GetLiveOrders200ResponseOrdersInner) SetCompanyName(v string) {
	o.CompanyName = &v
}

// GetStatus returns the Status field value if set, zero value otherwise.
func (o *GetLiveOrders200ResponseOrdersInner) GetStatus() string {
	if o == nil || IsNil(o.Status) {
		var ret string
		return ret
	}
	return *o.Status
}

// GetStatusOk returns a tuple with the Status field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetLiveOrders200ResponseOrdersInner) GetStatusOk() (*string, bool) {
	if o == nil || IsNil(o.Status) {
		return nil, false
	}
	return o.Status, true
}

// HasStatus returns a boolean if a field has been set.
func (o *GetLiveOrders200ResponseOrdersInner) HasStatus() bool {
	if o != nil && !IsNil(o.Status) {
		return true
	}

	return false
}

// SetStatus gets a reference to the given string and assigns it to the Status field.
func (o *GetLiveOrders200ResponseOrdersInner) SetStatus(v string) {
	o.Status = &v
}

// GetOrigOrderType returns the OrigOrderType field value if set, zero value otherwise.
func (o *GetLiveOrders200ResponseOrdersInner) GetOrigOrderType() string {
	if o == nil || IsNil(o.OrigOrderType) {
		var ret string
		return ret
	}
	return *o.OrigOrderType
}

// GetOrigOrderTypeOk returns a tuple with the OrigOrderType field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetLiveOrders200ResponseOrdersInner) GetOrigOrderTypeOk() (*string, bool) {
	if o == nil || IsNil(o.OrigOrderType) {
		return nil, false
	}
	return o.OrigOrderType, true
}

// HasOrigOrderType returns a boolean if a field has been set.
func (o *GetLiveOrders200ResponseOrdersInner) HasOrigOrderType() bool {
	if o != nil && !IsNil(o.OrigOrderType) {
		return true
	}

	return false
}

// SetOrigOrderType gets a reference to the given string and assigns it to the OrigOrderType field.
func (o *GetLiveOrders200ResponseOrdersInner) SetOrigOrderType(v string) {
	o.OrigOrderType = &v
}

// GetSupportsTaxOpt returns the SupportsTaxOpt field value if set, zero value otherwise.
func (o *GetLiveOrders200ResponseOrdersInner) GetSupportsTaxOpt() float32 {
	if o == nil || IsNil(o.SupportsTaxOpt) {
		var ret float32
		return ret
	}
	return *o.SupportsTaxOpt
}

// GetSupportsTaxOptOk returns a tuple with the SupportsTaxOpt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetLiveOrders200ResponseOrdersInner) GetSupportsTaxOptOk() (*float32, bool) {
	if o == nil || IsNil(o.SupportsTaxOpt) {
		return nil, false
	}
	return o.SupportsTaxOpt, true
}

// HasSupportsTaxOpt returns a boolean if a field has been set.
func (o *GetLiveOrders200ResponseOrdersInner) HasSupportsTaxOpt() bool {
	if o != nil && !IsNil(o.SupportsTaxOpt) {
		return true
	}

	return false
}

// SetSupportsTaxOpt gets a reference to the given float32 and assigns it to the SupportsTaxOpt field.
func (o *GetLiveOrders200ResponseOrdersInner) SetSupportsTaxOpt(v float32) {
	o.SupportsTaxOpt = &v
}

// GetLastExecutionTime returns the LastExecutionTime field value if set, zero value otherwise.
func (o *GetLiveOrders200ResponseOrdersInner) GetLastExecutionTime() float32 {
	if o == nil || IsNil(o.LastExecutionTime) {
		var ret float32
		return ret
	}
	return *o.LastExecutionTime
}

// GetLastExecutionTimeOk returns a tuple with the LastExecutionTime field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetLiveOrders200ResponseOrdersInner) GetLastExecutionTimeOk() (*float32, bool) {
	if o == nil || IsNil(o.LastExecutionTime) {
		return nil, false
	}
	return o.LastExecutionTime, true
}

// HasLastExecutionTime returns a boolean if a field has been set.
func (o *GetLiveOrders200ResponseOrdersInner) HasLastExecutionTime() bool {
	if o != nil && !IsNil(o.LastExecutionTime) {
		return true
	}

	return false
}

// SetLastExecutionTime gets a reference to the given float32 and assigns it to the LastExecutionTime field.
func (o *GetLiveOrders200ResponseOrdersInner) SetLastExecutionTime(v float32) {
	o.LastExecutionTime = &v
}

// GetLastExecutionTimeR returns the LastExecutionTimeR field value if set, zero value otherwise.
func (o *GetLiveOrders200ResponseOrdersInner) GetLastExecutionTimeR() float32 {
	if o == nil || IsNil(o.LastExecutionTimeR) {
		var ret float32
		return ret
	}
	return *o.LastExecutionTimeR
}

// GetLastExecutionTimeROk returns a tuple with the LastExecutionTimeR field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetLiveOrders200ResponseOrdersInner) GetLastExecutionTimeROk() (*float32, bool) {
	if o == nil || IsNil(o.LastExecutionTimeR) {
		return nil, false
	}
	return o.LastExecutionTimeR, true
}

// HasLastExecutionTimeR returns a boolean if a field has been set.
func (o *GetLiveOrders200ResponseOrdersInner) HasLastExecutionTimeR() bool {
	if o != nil && !IsNil(o.LastExecutionTimeR) {
		return true
	}

	return false
}

// SetLastExecutionTimeR gets a reference to the given float32 and assigns it to the LastExecutionTimeR field.
func (o *GetLiveOrders200ResponseOrdersInner) SetLastExecutionTimeR(v float32) {
	o.LastExecutionTimeR = &v
}

// GetOrderType returns the OrderType field value if set, zero value otherwise.
func (o *GetLiveOrders200ResponseOrdersInner) GetOrderType() string {
	if o == nil || IsNil(o.OrderType) {
		var ret string
		return ret
	}
	return *o.OrderType
}

// GetOrderTypeOk returns a tuple with the OrderType field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetLiveOrders200ResponseOrdersInner) GetOrderTypeOk() (*string, bool) {
	if o == nil || IsNil(o.OrderType) {
		return nil, false
	}
	return o.OrderType, true
}

// HasOrderType returns a boolean if a field has been set.
func (o *GetLiveOrders200ResponseOrdersInner) HasOrderType() bool {
	if o != nil && !IsNil(o.OrderType) {
		return true
	}

	return false
}

// SetOrderType gets a reference to the given string and assigns it to the OrderType field.
func (o *GetLiveOrders200ResponseOrdersInner) SetOrderType(v string) {
	o.OrderType = &v
}

// GetOrderRef returns the OrderRef field value if set, zero value otherwise.
func (o *GetLiveOrders200ResponseOrdersInner) GetOrderRef() string {
	if o == nil || IsNil(o.OrderRef) {
		var ret string
		return ret
	}
	return *o.OrderRef
}

// GetOrderRefOk returns a tuple with the OrderRef field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetLiveOrders200ResponseOrdersInner) GetOrderRefOk() (*string, bool) {
	if o == nil || IsNil(o.OrderRef) {
		return nil, false
	}
	return o.OrderRef, true
}

// HasOrderRef returns a boolean if a field has been set.
func (o *GetLiveOrders200ResponseOrdersInner) HasOrderRef() bool {
	if o != nil && !IsNil(o.OrderRef) {
		return true
	}

	return false
}

// SetOrderRef gets a reference to the given string and assigns it to the OrderRef field.
func (o *GetLiveOrders200ResponseOrdersInner) SetOrderRef(v string) {
	o.OrderRef = &v
}

// GetSide returns the Side field value if set, zero value otherwise.
func (o *GetLiveOrders200ResponseOrdersInner) GetSide() string {
	if o == nil || IsNil(o.Side) {
		var ret string
		return ret
	}
	return *o.Side
}

// GetSideOk returns a tuple with the Side field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetLiveOrders200ResponseOrdersInner) GetSideOk() (*string, bool) {
	if o == nil || IsNil(o.Side) {
		return nil, false
	}
	return o.Side, true
}

// HasSide returns a boolean if a field has been set.
func (o *GetLiveOrders200ResponseOrdersInner) HasSide() bool {
	if o != nil && !IsNil(o.Side) {
		return true
	}

	return false
}

// SetSide gets a reference to the given string and assigns it to the Side field.
func (o *GetLiveOrders200ResponseOrdersInner) SetSide(v string) {
	o.Side = &v
}

// GetTimeInForce returns the TimeInForce field value if set, zero value otherwise.
func (o *GetLiveOrders200ResponseOrdersInner) GetTimeInForce() string {
	if o == nil || IsNil(o.TimeInForce) {
		var ret string
		return ret
	}
	return *o.TimeInForce
}

// GetTimeInForceOk returns a tuple with the TimeInForce field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetLiveOrders200ResponseOrdersInner) GetTimeInForceOk() (*string, bool) {
	if o == nil || IsNil(o.TimeInForce) {
		return nil, false
	}
	return o.TimeInForce, true
}

// HasTimeInForce returns a boolean if a field has been set.
func (o *GetLiveOrders200ResponseOrdersInner) HasTimeInForce() bool {
	if o != nil && !IsNil(o.TimeInForce) {
		return true
	}

	return false
}

// SetTimeInForce gets a reference to the given string and assigns it to the TimeInForce field.
func (o *GetLiveOrders200ResponseOrdersInner) SetTimeInForce(v string) {
	o.TimeInForce = &v
}

// GetPrice returns the Price field value if set, zero value otherwise.
func (o *GetLiveOrders200ResponseOrdersInner) GetPrice() float32 {
	if o == nil || IsNil(o.Price) {
		var ret float32
		return ret
	}
	return *o.Price
}

// GetPriceOk returns a tuple with the Price field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetLiveOrders200ResponseOrdersInner) GetPriceOk() (*float32, bool) {
	if o == nil || IsNil(o.Price) {
		return nil, false
	}
	return o.Price, true
}

// HasPrice returns a boolean if a field has been set.
func (o *GetLiveOrders200ResponseOrdersInner) HasPrice() bool {
	if o != nil && !IsNil(o.Price) {
		return true
	}

	return false
}

// SetPrice gets a reference to the given float32 and assigns it to the Price field.
func (o *GetLiveOrders200ResponseOrdersInner) SetPrice(v float32) {
	o.Price = &v
}

// GetBgColor returns the BgColor field value if set, zero value otherwise.
func (o *GetLiveOrders200ResponseOrdersInner) GetBgColor() string {
	if o == nil || IsNil(o.BgColor) {
		var ret string
		return ret
	}
	return *o.BgColor
}

// GetBgColorOk returns a tuple with the BgColor field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetLiveOrders200ResponseOrdersInner) GetBgColorOk() (*string, bool) {
	if o == nil || IsNil(o.BgColor) {
		return nil, false
	}
	return o.BgColor, true
}

// HasBgColor returns a boolean if a field has been set.
func (o *GetLiveOrders200ResponseOrdersInner) HasBgColor() bool {
	if o != nil && !IsNil(o.BgColor) {
		return true
	}

	return false
}

// SetBgColor gets a reference to the given string and assigns it to the BgColor field.
func (o *GetLiveOrders200ResponseOrdersInner) SetBgColor(v string) {
	o.BgColor = &v
}

// GetFgColor returns the FgColor field value if set, zero value otherwise.
func (o *GetLiveOrders200ResponseOrdersInner) GetFgColor() string {
	if o == nil || IsNil(o.FgColor) {
		var ret string
		return ret
	}
	return *o.FgColor
}

// GetFgColorOk returns a tuple with the FgColor field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetLiveOrders200ResponseOrdersInner) GetFgColorOk() (*string, bool) {
	if o == nil || IsNil(o.FgColor) {
		return nil, false
	}
	return o.FgColor, true
}

// HasFgColor returns a boolean if a field has been set.
func (o *GetLiveOrders200ResponseOrdersInner) HasFgColor() bool {
	if o != nil && !IsNil(o.FgColor) {
		return true
	}

	return false
}

// SetFgColor gets a reference to the given string and assigns it to the FgColor field.
func (o *GetLiveOrders200ResponseOrdersInner) SetFgColor(v string) {
	o.FgColor = &v
}

func (o GetLiveOrders200ResponseOrdersInner) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetLiveOrders200ResponseOrdersInner) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Acct) {
		toSerialize["acct"] = o.Acct
	}
	if !IsNil(o.Conidex) {
		toSerialize["conidex"] = o.Conidex
	}
	if !IsNil(o.Conid) {
		toSerialize["conid"] = o.Conid
	}
	if !IsNil(o.OrderId) {
		toSerialize["orderId"] = o.OrderId
	}
	if !IsNil(o.CashCcy) {
		toSerialize["cashCcy"] = o.CashCcy
	}
	if !IsNil(o.SizeAndFills) {
		toSerialize["sizeAndFills"] = o.SizeAndFills
	}
	if !IsNil(o.OrderDesc) {
		toSerialize["orderDesc"] = o.OrderDesc
	}
	if !IsNil(o.Description1) {
		toSerialize["description1"] = o.Description1
	}
	if !IsNil(o.Ticker) {
		toSerialize["ticker"] = o.Ticker
	}
	if !IsNil(o.SecType) {
		toSerialize["secType"] = o.SecType
	}
	if !IsNil(o.ListingExchange) {
		toSerialize["listingExchange"] = o.ListingExchange
	}
	if !IsNil(o.RemainingQuantity) {
		toSerialize["remainingQuantity"] = o.RemainingQuantity
	}
	if !IsNil(o.FilledQuantity) {
		toSerialize["filledQuantity"] = o.FilledQuantity
	}
	if !IsNil(o.CompanyName) {
		toSerialize["companyName"] = o.CompanyName
	}
	if !IsNil(o.Status) {
		toSerialize["status"] = o.Status
	}
	if !IsNil(o.OrigOrderType) {
		toSerialize["origOrderType"] = o.OrigOrderType
	}
	if !IsNil(o.SupportsTaxOpt) {
		toSerialize["supportsTaxOpt"] = o.SupportsTaxOpt
	}
	if !IsNil(o.LastExecutionTime) {
		toSerialize["lastExecutionTime"] = o.LastExecutionTime
	}
	if !IsNil(o.LastExecutionTimeR) {
		toSerialize["lastExecutionTime_r"] = o.LastExecutionTimeR
	}
	if !IsNil(o.OrderType) {
		toSerialize["orderType"] = o.OrderType
	}
	if !IsNil(o.OrderRef) {
		toSerialize["order_ref"] = o.OrderRef
	}
	if !IsNil(o.Side) {
		toSerialize["side"] = o.Side
	}
	if !IsNil(o.TimeInForce) {
		toSerialize["timeInForce"] = o.TimeInForce
	}
	if !IsNil(o.Price) {
		toSerialize["price"] = o.Price
	}
	if !IsNil(o.BgColor) {
		toSerialize["bgColor"] = o.BgColor
	}
	if !IsNil(o.FgColor) {
		toSerialize["fgColor"] = o.FgColor
	}
	return toSerialize, nil
}

type NullableGetLiveOrders200ResponseOrdersInner struct {
	value *GetLiveOrders200ResponseOrdersInner
	isSet bool
}

func (v NullableGetLiveOrders200ResponseOrdersInner) Get() *GetLiveOrders200ResponseOrdersInner {
	return v.value
}

func (v *NullableGetLiveOrders200ResponseOrdersInner) Set(val *GetLiveOrders200ResponseOrdersInner) {
	v.value = val
	v.isSet = true
}

func (v NullableGetLiveOrders200ResponseOrdersInner) IsSet() bool {
	return v.isSet
}

func (v *NullableGetLiveOrders200ResponseOrdersInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetLiveOrders200ResponseOrdersInner(val *GetLiveOrders200ResponseOrdersInner) *NullableGetLiveOrders200ResponseOrdersInner {
	return &NullableGetLiveOrders200ResponseOrdersInner{value: val, isSet: true}
}

func (v NullableGetLiveOrders200ResponseOrdersInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetLiveOrders200ResponseOrdersInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
