/*
Client Portal Web API

Client Poral Web API

API version: 1.0.0
Contact: e@e.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

import (
	"encoding/json"
)

// checks if the IserverAccountAccountIdOrderWhatifPost200ResponseEquity type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &IserverAccountAccountIdOrderWhatifPost200ResponseEquity{}

// IserverAccountAccountIdOrderWhatifPost200ResponseEquity struct for IserverAccountAccountIdOrderWhatifPost200ResponseEquity
type IserverAccountAccountIdOrderWhatifPost200ResponseEquity struct {
	Current *string `json:"current,omitempty"`
	Change  *string `json:"change,omitempty"`
	After   *string `json:"after,omitempty"`
}

// NewIserverAccountAccountIdOrderWhatifPost200ResponseEquity instantiates a new IserverAccountAccountIdOrderWhatifPost200ResponseEquity object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewIserverAccountAccountIdOrderWhatifPost200ResponseEquity() *IserverAccountAccountIdOrderWhatifPost200ResponseEquity {
	this := IserverAccountAccountIdOrderWhatifPost200ResponseEquity{}
	return &this
}

// NewIserverAccountAccountIdOrderWhatifPost200ResponseEquityWithDefaults instantiates a new IserverAccountAccountIdOrderWhatifPost200ResponseEquity object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewIserverAccountAccountIdOrderWhatifPost200ResponseEquityWithDefaults() *IserverAccountAccountIdOrderWhatifPost200ResponseEquity {
	this := IserverAccountAccountIdOrderWhatifPost200ResponseEquity{}
	return &this
}

// GetCurrent returns the Current field value if set, zero value otherwise.
func (o *IserverAccountAccountIdOrderWhatifPost200ResponseEquity) GetCurrent() string {
	if o == nil || IsNil(o.Current) {
		var ret string
		return ret
	}
	return *o.Current
}

// GetCurrentOk returns a tuple with the Current field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *IserverAccountAccountIdOrderWhatifPost200ResponseEquity) GetCurrentOk() (*string, bool) {
	if o == nil || IsNil(o.Current) {
		return nil, false
	}
	return o.Current, true
}

// HasCurrent returns a boolean if a field has been set.
func (o *IserverAccountAccountIdOrderWhatifPost200ResponseEquity) HasCurrent() bool {
	if o != nil && !IsNil(o.Current) {
		return true
	}

	return false
}

// SetCurrent gets a reference to the given string and assigns it to the Current field.
func (o *IserverAccountAccountIdOrderWhatifPost200ResponseEquity) SetCurrent(v string) {
	o.Current = &v
}

// GetChange returns the Change field value if set, zero value otherwise.
func (o *IserverAccountAccountIdOrderWhatifPost200ResponseEquity) GetChange() string {
	if o == nil || IsNil(o.Change) {
		var ret string
		return ret
	}
	return *o.Change
}

// GetChangeOk returns a tuple with the Change field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *IserverAccountAccountIdOrderWhatifPost200ResponseEquity) GetChangeOk() (*string, bool) {
	if o == nil || IsNil(o.Change) {
		return nil, false
	}
	return o.Change, true
}

// HasChange returns a boolean if a field has been set.
func (o *IserverAccountAccountIdOrderWhatifPost200ResponseEquity) HasChange() bool {
	if o != nil && !IsNil(o.Change) {
		return true
	}

	return false
}

// SetChange gets a reference to the given string and assigns it to the Change field.
func (o *IserverAccountAccountIdOrderWhatifPost200ResponseEquity) SetChange(v string) {
	o.Change = &v
}

// GetAfter returns the After field value if set, zero value otherwise.
func (o *IserverAccountAccountIdOrderWhatifPost200ResponseEquity) GetAfter() string {
	if o == nil || IsNil(o.After) {
		var ret string
		return ret
	}
	return *o.After
}

// GetAfterOk returns a tuple with the After field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *IserverAccountAccountIdOrderWhatifPost200ResponseEquity) GetAfterOk() (*string, bool) {
	if o == nil || IsNil(o.After) {
		return nil, false
	}
	return o.After, true
}

// HasAfter returns a boolean if a field has been set.
func (o *IserverAccountAccountIdOrderWhatifPost200ResponseEquity) HasAfter() bool {
	if o != nil && !IsNil(o.After) {
		return true
	}

	return false
}

// SetAfter gets a reference to the given string and assigns it to the After field.
func (o *IserverAccountAccountIdOrderWhatifPost200ResponseEquity) SetAfter(v string) {
	o.After = &v
}

func (o IserverAccountAccountIdOrderWhatifPost200ResponseEquity) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o IserverAccountAccountIdOrderWhatifPost200ResponseEquity) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Current) {
		toSerialize["current"] = o.Current
	}
	if !IsNil(o.Change) {
		toSerialize["change"] = o.Change
	}
	if !IsNil(o.After) {
		toSerialize["after"] = o.After
	}
	return toSerialize, nil
}

type NullableIserverAccountAccountIdOrderWhatifPost200ResponseEquity struct {
	value *IserverAccountAccountIdOrderWhatifPost200ResponseEquity
	isSet bool
}

func (v NullableIserverAccountAccountIdOrderWhatifPost200ResponseEquity) Get() *IserverAccountAccountIdOrderWhatifPost200ResponseEquity {
	return v.value
}

func (v *NullableIserverAccountAccountIdOrderWhatifPost200ResponseEquity) Set(val *IserverAccountAccountIdOrderWhatifPost200ResponseEquity) {
	v.value = val
	v.isSet = true
}

func (v NullableIserverAccountAccountIdOrderWhatifPost200ResponseEquity) IsSet() bool {
	return v.isSet
}

func (v *NullableIserverAccountAccountIdOrderWhatifPost200ResponseEquity) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableIserverAccountAccountIdOrderWhatifPost200ResponseEquity(val *IserverAccountAccountIdOrderWhatifPost200ResponseEquity) *NullableIserverAccountAccountIdOrderWhatifPost200ResponseEquity {
	return &NullableIserverAccountAccountIdOrderWhatifPost200ResponseEquity{value: val, isSet: true}
}

func (v NullableIserverAccountAccountIdOrderWhatifPost200ResponseEquity) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableIserverAccountAccountIdOrderWhatifPost200ResponseEquity) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
