/*
Client Portal Web API

Client Poral Web API

API version: 1.0.0
Contact: e@e.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

import (
	"encoding/json"
)

// checks if the IserverContractConidAlgosGet200ResponseInner type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &IserverContractConidAlgosGet200ResponseInner{}

// IserverContractConidAlgosGet200ResponseInner struct for IserverContractConidAlgosGet200ResponseInner
type IserverContractConidAlgosGet200ResponseInner struct {
	Name        *string                                                       `json:"name,omitempty"`
	Description *string                                                       `json:"description,omitempty"`
	Id          *string                                                       `json:"id,omitempty"`
	Parameters  []IserverContractConidAlgosGet200ResponseInnerParametersInner `json:"parameters,omitempty"`
}

// NewIserverContractConidAlgosGet200ResponseInner instantiates a new IserverContractConidAlgosGet200ResponseInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewIserverContractConidAlgosGet200ResponseInner() *IserverContractConidAlgosGet200ResponseInner {
	this := IserverContractConidAlgosGet200ResponseInner{}
	return &this
}

// NewIserverContractConidAlgosGet200ResponseInnerWithDefaults instantiates a new IserverContractConidAlgosGet200ResponseInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewIserverContractConidAlgosGet200ResponseInnerWithDefaults() *IserverContractConidAlgosGet200ResponseInner {
	this := IserverContractConidAlgosGet200ResponseInner{}
	return &this
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *IserverContractConidAlgosGet200ResponseInner) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *IserverContractConidAlgosGet200ResponseInner) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *IserverContractConidAlgosGet200ResponseInner) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *IserverContractConidAlgosGet200ResponseInner) SetName(v string) {
	o.Name = &v
}

// GetDescription returns the Description field value if set, zero value otherwise.
func (o *IserverContractConidAlgosGet200ResponseInner) GetDescription() string {
	if o == nil || IsNil(o.Description) {
		var ret string
		return ret
	}
	return *o.Description
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *IserverContractConidAlgosGet200ResponseInner) GetDescriptionOk() (*string, bool) {
	if o == nil || IsNil(o.Description) {
		return nil, false
	}
	return o.Description, true
}

// HasDescription returns a boolean if a field has been set.
func (o *IserverContractConidAlgosGet200ResponseInner) HasDescription() bool {
	if o != nil && !IsNil(o.Description) {
		return true
	}

	return false
}

// SetDescription gets a reference to the given string and assigns it to the Description field.
func (o *IserverContractConidAlgosGet200ResponseInner) SetDescription(v string) {
	o.Description = &v
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *IserverContractConidAlgosGet200ResponseInner) GetId() string {
	if o == nil || IsNil(o.Id) {
		var ret string
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *IserverContractConidAlgosGet200ResponseInner) GetIdOk() (*string, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *IserverContractConidAlgosGet200ResponseInner) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given string and assigns it to the Id field.
func (o *IserverContractConidAlgosGet200ResponseInner) SetId(v string) {
	o.Id = &v
}

// GetParameters returns the Parameters field value if set, zero value otherwise.
func (o *IserverContractConidAlgosGet200ResponseInner) GetParameters() []IserverContractConidAlgosGet200ResponseInnerParametersInner {
	if o == nil || IsNil(o.Parameters) {
		var ret []IserverContractConidAlgosGet200ResponseInnerParametersInner
		return ret
	}
	return o.Parameters
}

// GetParametersOk returns a tuple with the Parameters field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *IserverContractConidAlgosGet200ResponseInner) GetParametersOk() ([]IserverContractConidAlgosGet200ResponseInnerParametersInner, bool) {
	if o == nil || IsNil(o.Parameters) {
		return nil, false
	}
	return o.Parameters, true
}

// HasParameters returns a boolean if a field has been set.
func (o *IserverContractConidAlgosGet200ResponseInner) HasParameters() bool {
	if o != nil && !IsNil(o.Parameters) {
		return true
	}

	return false
}

// SetParameters gets a reference to the given []IserverContractConidAlgosGet200ResponseInnerParametersInner and assigns it to the Parameters field.
func (o *IserverContractConidAlgosGet200ResponseInner) SetParameters(v []IserverContractConidAlgosGet200ResponseInnerParametersInner) {
	o.Parameters = v
}

func (o IserverContractConidAlgosGet200ResponseInner) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o IserverContractConidAlgosGet200ResponseInner) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	if !IsNil(o.Description) {
		toSerialize["description"] = o.Description
	}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	if !IsNil(o.Parameters) {
		toSerialize["parameters"] = o.Parameters
	}
	return toSerialize, nil
}

type NullableIserverContractConidAlgosGet200ResponseInner struct {
	value *IserverContractConidAlgosGet200ResponseInner
	isSet bool
}

func (v NullableIserverContractConidAlgosGet200ResponseInner) Get() *IserverContractConidAlgosGet200ResponseInner {
	return v.value
}

func (v *NullableIserverContractConidAlgosGet200ResponseInner) Set(val *IserverContractConidAlgosGet200ResponseInner) {
	v.value = val
	v.isSet = true
}

func (v NullableIserverContractConidAlgosGet200ResponseInner) IsSet() bool {
	return v.isSet
}

func (v *NullableIserverContractConidAlgosGet200ResponseInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableIserverContractConidAlgosGet200ResponseInner(val *IserverContractConidAlgosGet200ResponseInner) *NullableIserverContractConidAlgosGet200ResponseInner {
	return &NullableIserverContractConidAlgosGet200ResponseInner{value: val, isSet: true}
}

func (v NullableIserverContractConidAlgosGet200ResponseInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableIserverContractConidAlgosGet200ResponseInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
